version: '3'
services:
  # my-app:
  # image: ${docker-registry}/my-app:1.0
  # ports:
  # - 3000:3000
  mongodb:
    image: mongo #if the image is from private repo we have to provide the whole path for the image file. not needed if coming from dcker hub.
    ports:
      - 27017:27017

    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes: #specification of the named volume specific to this container
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081 #host port:container port
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes: #this local volume is to be used by ALL or ANY of the services. hence specified here
  mongo-data:
    driver: local # this specified that it is a local storage.

